class AESeeder
  def self.create_char_classes
    CharClass.delete_all
    CharClass.create(:name => 'Akashic',        :hit_die => '1d6')
    CharClass.create(:name => 'Champion',       :hit_die => '1d10')
    CharClass.create(:name => 'Greenbond',      :hit_die => '1d6')
    CharClass.create(:name => 'Mage Blade',     :hit_die => '1d8')
    CharClass.create(:name => 'Magister',       :hit_die => '1d6')
    CharClass.create(:name => 'Oathsworn',      :hit_die => '1d10')
    CharClass.create(:name => 'Ritual Warrior', :hit_die => '1d10')
    CharClass.create(:name => 'Runethane',      :hit_die => '1d6')
    CharClass.create(:name => 'Totem Warrior',  :hit_die => '1d8')
    CharClass.create(:name => 'Unfettered',     :hit_die => '1d8')
    CharClass.create(:name => 'Witch',          :hit_die => '1d6')
    CharClass.create(:name => 'Warmain',        :hit_die => '1d12')
  end

  def self.create_feat
    Feat.delete_all
    GeneralFeat.create(:name => 'Ability Focus')
    GeneralFeat.create(:name => 'Aid Spellcasting')
    GeneralFeat.create(:name => 'Armor Proficiency, Exotic')
    GeneralFeat.create(:name => 'Armor Proficiency, Heavy')
    GeneralFeat.create(:name => 'Armor Proficiency, Light')
    GeneralFeat.create(:name => 'Armor Proficiency, Medium')
    GeneralFeat.create(:name => 'Bite')
    GeneralFeat.create(:name => 'Bloody Strike')
    GeneralFeat.create(:name => 'Cleave')
    GeneralFeat.create(:name => 'Combat Reflexes')
    GeneralFeat.create(:name => 'Compensate for Size')
    GeneralFeat.create(:name => 'Complex Spell')
    GeneralFeat.create(:name => 'Conjure Mastery')
    GeneralFeat.create(:name => 'Defensive Move')
    GeneralFeat.create(:name => 'Defensive Stance')
    GeneralFeat.create(:name => 'Empower Spell-like Ability')
    GeneralFeat.create(:name => 'Exotic Spell')
    GeneralFeat.create(:name => 'Expertise')
    GeneralFeat.create(:name => 'Far Shot')
    GeneralFeat.create(:name => 'First Strike')
    GeneralFeat.create(:name => 'Flail Defense')
    GeneralFeat.create(:name => 'Flyby Attack')
    GeneralFeat.create(:name => 'Great Fortitude')
    GeneralFeat.create(:name => 'Improved Bull Rush')
    GeneralFeat.create(:name => 'Improved Critical')
    GeneralFeat.create(:name => 'Improved Disarm')
    GeneralFeat.create(:name => 'Improved Initiative')
    GeneralFeat.create(:name => 'Improved Sunder')
    GeneralFeat.create(:name => 'Improved Trip')
    GeneralFeat.create(:name => 'Iron Will')
    GeneralFeat.create(:name => 'Lightning Reflexes')
    GeneralFeat.create(:name => 'Low Blow')
    GeneralFeat.create(:name => 'Mobility')
    GeneralFeat.create(:name => 'Modify Combat Style')
    GeneralFeat.create(:name => 'Modify Spell')
    GeneralFeat.create(:name => 'Mounted Archery')
    GeneralFeat.create(:name => 'Mounted Combat')
    GeneralFeat.create(:name => 'Paralyzing Blow')
    GeneralFeat.create(:name => 'Point Blank Shot')
    GeneralFeat.create(:name => 'Power Attack')
    GeneralFeat.create(:name => 'Power Charge')
    GeneralFeat.create(:name => 'Precise Shot')
    GeneralFeat.create(:name => 'Quick Draw')
    GeneralFeat.create(:name => 'Quicken Spell-like Ability')
    GeneralFeat.create(:name => 'Rapid Strike')
    GeneralFeat.create(:name => 'Ride-by Attack')
    GeneralFeat.create(:name => 'Shield Proficiency')
    GeneralFeat.create(:name => 'Shield Specialization')
    GeneralFeat.create(:name => 'Shot on the Run')
    GeneralFeat.create(:name => 'Skill Focus')
    GeneralFeat.create(:name => 'Speed Burst')
    GeneralFeat.create(:name => 'Stomp')
    GeneralFeat.create(:name => 'Stunning Blow')
    GeneralFeat.create(:name => 'Sturdy')
    GeneralFeat.create(:name => 'Tough Hide')
    GeneralFeat.create(:name => 'Track')
    GeneralFeat.create(:name => 'Trample')
    GeneralFeat.create(:name => 'Two-Weapon Defense')
    GeneralFeat.create(:name => 'Two-Weapon Fighting')
    GeneralFeat.create(:name => 'Two-Weapon Fighting, Massive')
    GeneralFeat.create(:name => 'Unarmed Strike, Defensive')
    GeneralFeat.create(:name => 'Unarmed Strike, Mighty')
    GeneralFeat.create(:name => 'Weapon Finesse')
    GeneralFeat.create(:name => 'Weapon Focus')
    GeneralFeat.create(:name => 'Weapon Proficiency, Exotic')
    GeneralFeat.create(:name => 'Weapon Proficiency, Simple')
    CeremonialFeat.create(:name => 'Attune to Magic Item')
    CeremonialFeat.create(:name => 'Battle Mage')
    CeremonialFeat.create(:name => 'Blessed Mage')
    CeremonialFeat.create(:name => 'Blood as Power')
    CeremonialFeat.create(:name => 'Bonded Item')
    CeremonialFeat.create(:name => 'Brandish Magical Might')
    CeremonialFeat.create(:name => 'Chi-Julud')
    CeremonialFeat.create(:name => 'Corrupt Mage')
    CeremonialFeat.create(:name => 'Creator Mage')
    CeremonialFeat.create(:name => 'Crippling Strike')
    CeremonialFeat.create(:name => 'Defensive Roll')
    CeremonialFeat.create(:name => 'Dragon Mage')
    CeremonialFeat.create(:name => 'Eldritch Training')
    CeremonialFeat.create(:name => 'Elemental Mage')
    CeremonialFeat.create(:name => 'Energy Mage')
    CeremonialFeat.create(:name => 'Fey Mage')
    CeremonialFeat.create(:name => 'Fleet of Foot')
    CeremonialFeat.create(:name => 'Focused Healing')
    CeremonialFeat.create(:name => 'Giantish Mage')
    CeremonialFeat.create(:name => 'Hands as Weapons')
    CeremonialFeat.create(:name => 'Hunter Mage')
    CeremonialFeat.create(:name => 'Infuse Weapon')
    CeremonialFeat.create(:name => 'Intuitive Sense')
    CeremonialFeat.create(:name => 'Iron Flesh')
    CeremonialFeat.create(:name => 'Litorian Mage')
    CeremonialFeat.create(:name => 'Mighty Hurl')
    CeremonialFeat.create(:name => 'Mirror Sight')
    CeremonialFeat.create(:name => 'Opportunist')
    CeremonialFeat.create(:name => 'Peaceful Mage')
    CeremonialFeat.create(:name => 'Power of the Name')
    CeremonialFeat.create(:name => 'Priest')
    CeremonialFeat.create(:name => 'Psion')
    CeremonialFeat.create(:name => 'Quicken Spell')
    CeremonialFeat.create(:name => 'Rapid Reload')
    CeremonialFeat.create(:name => 'Resistant Spell')
    CeremonialFeat.create(:name => 'Ritual Combat')
    CeremonialFeat.create(:name => 'Runecaster')
    CeremonialFeat.create(:name => 'Sanctum')
    CeremonialFeat.create(:name => 'Sense the Unseen')
    CeremonialFeat.create(:name => 'Sibeccai Mage')
    CeremonialFeat.create(:name => 'Skill Application')
    CeremonialFeat.create(:name => 'Skill Mastery')
    CeremonialFeat.create(:name => 'Slippery Mind')
    CeremonialFeat.create(:name => 'Tatooed Spell')
    CeremonialFeat.create(:name => 'Title')
    CeremonialFeat.create(:name => 'Unraveling Mage')
    CeremonialFeat.create(:name => 'Weapon Specialization')
    CeremonialFeat.create(:name => 'Whirlwind Attack')
    CeremonialFeat.create(:name => 'Wild Mage')
    ItemCreationFeat.create(:name => 'Craft Charged Item')
    ItemCreationFeat.create(:name => 'Craft Constant Item')
    ItemCreationFeat.create(:name => 'Craft Magic Arms and Armor')
    ItemCreationFeat.create(:name => 'Craft Single-Use Item')
    ItemCreationFeat.create(:name => 'Craft Spell-Completion Item')
    ItemCreationFeat.create(:name => 'Affinity with Skill')
    TalentFeat.create(:name => 'Ambidexterity')
    TalentFeat.create(:name => 'Born Hero')
    TalentFeat.create(:name => 'Born Leader')
    TalentFeat.create(:name => 'Defensive')
    TalentFeat.create(:name => 'Eidetic Memory')
    TalentFeat.create(:name => 'Elemental Resistance')
    TalentFeat.create(:name => 'Energy Resistance')
    TalentFeat.create(:name => 'Fast Healer')
    TalentFeat.create(:name => 'Light Sleeper')
    TalentFeat.create(:name => 'Natural Archer')
    TalentFeat.create(:name => 'Natural Swordsman')
    TalentFeat.create(:name => 'Night Owl')
    TalentFeat.create(:name => 'Resistance to Disease')
    TalentFeat.create(:name => 'Resistance to Magic')
    TalentFeat.create(:name => 'Resistance to Poison')
    TalentFeat.create(:name => 'Sensitive')
    TalentFeat.create(:name => 'Signature Spell')
    TalentFeat.create(:name => 'Spell Affinity')
    TalentFeat.create(:name => 'Spell Artist')
    TalentFeat.create(:name => 'Unique Spell')
    TalentFeat.create(:name => 'The Voice')
    TalentFeat.create(:name => 'Way with Animals')
    TalentFeat.create(:name => 'Wealthy')
  end

  def self.create_races
    Race.delete_all
    Race.create(:name => 'Human')
    Race.create(:name => 'Dracha')
    Race.create(:name => 'Faen')
    Race.create(:name => 'Giant')
    Race.create(:name => 'Litorian')
    Race.create(:name => 'Mojh')
    Race.create(:name => 'Runechild')
    Race.create(:name => 'Sibeccai')
    Race.create(:name => 'Verrik')
  end

  def self.create_skill
    Skill.delete_all
    Skill.create(:name => 'Alchemy', :prop_id => @@int, :needs_training => true)
    Skill.create(:name => 'Appraise', :prop_id => @@int, :needs_training => false)
    Skill.create(:name => 'Balance', :prop_id => @@dex, :needs_training => false,
                  :benefits => 'misc_bonus += 2 if (character.Skill[\"Tumble\"].ranks >= 5)')
    Skill.create(:name => 'Bluff', :prop_id => @@cha, :needs_training => false)
    Skill.create(:name => 'Climb', :prop_id => @@str, :needs_training => false)
    Skill.create(:name => 'Concentration', :prop_id => @@con, :needs_training => false)
    Skill.create(:name => 'Craft', :prop_id => @@int, :needs_training => false)
    Skill.create(:name => 'Decipher Script', :prop_id => @@int, :needs_training => true)
    Skill.create(:name => 'Diplomacy', :prop_id => @@cha, :needs_training => false,
                  :benefits => 'misc_bonus += 2 if (character.Skill[\"Bluff\"].ranks >= 5) misc_bonus += 2 if (character.Skill[\"Sense Motive\"].ranks >= 5)')
    Skill.create(:name => 'Disable Device', :prop_id => @@int, :needs_training => true)
    Skill.create(:name => 'Disguise', :prop_id => @@cha, :needs_training => false,
                  :benefits => 'misc_bonus += 2 if (character.Skill[\"Bluff\"].ranks >= 5)')
    Skill.create(:name => 'Escape Artist', :prop_id => @@dex, :needs_training => false)
    Skill.create(:name => 'Forgery', :prop_id => @@int, :needs_training => false)
    Skill.create(:name => 'Gather Information', :prop_id => @@cha, :needs_training => false)
    Skill.create(:name => 'Handle Animal', :prop_id => @@cha, :needs_training => true)
    Skill.create(:name => 'Heal', :prop_id => @@wis, :needs_training => false,
                  :benefits => 'misc_bonus += 2 if (character.Skill[\"Knowledge (Nature)\"].ranks >= 5)')
    Skill.create(:name => 'Innuendo', :prop_id => @@wis, :needs_training => true)
    Skill.create(:name => 'Intimidate', :prop_id => @@cha, :needs_training => false,
                  :benefits => 'misc_bonus += 2 if (character.Skill[\"Bluff\"].ranks >= 5)')
    Skill.create(:name => 'Jump', :prop_id => @@str, :needs_training => false,
                  :benefits => 'misc_bonus += 2 if (character.Skill[\"Tumble\"].ranks >= 5)')
    Skill.create(:name => 'Knowledge (Architecture)', :prop_id => @@int, :needs_training => true)
    Skill.create(:name => 'Knowledge (Ceremony)', :prop_id => @@int, :needs_training => true)
    Skill.create(:name => 'Knowledge (Cosmology)', :prop_id => @@int, :needs_training => true)
    Skill.create(:name => 'Knowledge (Dangerous Beasts)', :prop_id => @@int, :needs_training => true)
    Skill.create(:name => 'Knowledge (Dracha)', :prop_id => @@int, :needs_training => true)
    Skill.create(:name => 'Knowledge (Dragons)', :prop_id => @@int, :needs_training => true)
    Skill.create(:name => 'Knowledge (Engineering)', :prop_id => @@int, :needs_training => true)
    Skill.create(:name => 'Knowledge (Faen)', :prop_id => @@int, :needs_training => true)
    Skill.create(:name => 'Knowledge (Geography)', :prop_id => @@int, :needs_training => true)
    Skill.create(:name => 'Knowledge (Giants)', :prop_id => @@int, :needs_training => true)
    Skill.create(:name => 'Knowledge (History)', :prop_id => @@int, :needs_training => true)
    Skill.create(:name => 'Knowledge (Humans)', :prop_id => @@int, :needs_training => true)
    Skill.create(:name => 'Knowledge (Litorians)', :prop_id => @@int, :needs_training => true)
    Skill.create(:name => 'Knowledge (Magic)', :prop_id => @@int, :needs_training => true)
    Skill.create(:name => 'Knowledge (Mojh)', :prop_id => @@int, :needs_training => true)
    Skill.create(:name => 'Knowledge (Nature)', :prop_id => @@int, :needs_training => true)
    Skill.create(:name => 'Knowledge (Nobility/Courtesy)', :prop_id => @@int, :needs_training => true)
    Skill.create(:name => 'Knowledge (Religion)', :prop_id => @@int, :needs_training => true)
    Skill.create(:name => 'Knowledge (Runes)', :prop_id => @@int, :needs_training => true)
    Skill.create(:name => 'Knowledge (Sailing/Navigation)', :prop_id => @@int, :needs_training => true)
    Skill.create(:name => 'Knowledge (Science)', :prop_id => @@int, :needs_training => true)
    Skill.create(:name => 'Knowledge (Sibeccai)', :prop_id => @@int, :needs_training => true)
    Skill.create(:name => 'Knowledge (Verrik)', :prop_id => @@int, :needs_training => true)
    Skill.create(:name => 'Listen', :prop_id => @@wis, :needs_training => false)
    Skill.create(:name => 'Open Lock', :prop_id => @@dex, :needs_training => true)
    Skill.create(:name => 'Perform', :prop_id => @@cha, :needs_training => false)
    Skill.create(:name => 'Ride', :prop_id => @@dex, :needs_training => false,
                  :benefits => 'misc_bonus += 2 if (character.Skill[\"Handle Animal\"].ranks >= 5)')
    Skill.create(:name => 'Search', :prop_id => @@int, :needs_training => false)
    Skill.create(:name => 'Sense Motive', :prop_id => @@wis, :needs_training => false)
    Skill.create(:name => 'Sleight of Hand', :prop_id => @@dex, :needs_training => true,
                  :benefits => 'misc_bonus += 2 if (character.Skill[\"Bluff\"].ranks >= 5)')
    Skill.create(:name => 'Sneak', :prop_id => @@dex, :needs_training => false)
    Skill.create(:name => 'Speak Language', :prop_id => @@int, :needs_training => true)
    Skill.create(:name => 'Spellcraft', :prop_id => @@int, :needs_training => true)
    Skill.create(:name => 'Spot', :prop_id => @@wis, :needs_training => false)
    Skill.create(:name => 'Survival', :prop_id => @@wis, :needs_training => false)
    Skill.create(:name => 'Swim', :prop_id => @@str, :needs_training => false)
    Skill.create(:name => 'Tumble', :prop_id => @@dex, :needs_training => true,
                  :benefits => 'misc_bonus += 2 if (character.Skill[\"Jump\"].ranks >= 5)')
    Skill.create(:name => 'Use Magic Device', :prop_id => @@cha, :needs_training => true)
    Skill.create(:name => 'Use Rope', :prop_id => @@dex, :needs_training => false)
  end

end


AESeeder.create_char_classes
AESeeder.create_feat
AESeeder.create_races
AESeeder.create_skill
